### ISSUE TITLE
Can't use it with CDN in HTML page

### ISSUE THREAD

**Issue by Mingliang2018** [fiduswriter/Simple-DataTables#39]
Hi Experts,

I created a simple HTML page with a table. 

Then insert the following CDN settings, in the local *.js file, I wrote "import {DataTable} from "simple-datatables"".  

but Chrome/Safari can't recognize the syntax "DataTable"

<link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" type="text/css">
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" type="text/javascript"></script>

NodeJS is not installed, the problem is how can we use it as the traditional DataTables.
The intention is to remove jQuery, so don't add the dependency to NPM.

Could someone help me? 
Thanks a lot!

Mingliang

**Comment by gmish27** [comment]
Following link from the demo works for me as a workaround:
https://unpkg.com/vanilla-datatables@latest/dist/vanilla-dataTables.min.js

**Comment by LianSheng197** [comment]
Hi, I just encounter same problem.
I refer to this writing from [demo/umd.html](https://github.com/fiduswriter/Simple-DataTables/blob/master/demo/umd.html#L136)

Just add `simpleDatatables.` in front of `DataTable`.

But it still can't solve problem -- if I follow the `readme.md` tutorial:
```
const myTable = document.querySelector("#myTable");
const dataTable = new simpleDatatables.DataTable(myTable);
```

It'll report
```
Uncaught TypeError: Cannot read property 'layout' of undefined
    at new DataTable (simple-datatables.js:8)
```

Finally I tried this ([here is original version](https://github.com/fiduswriter/Simple-DataTables/wiki/Plugins#usage)), it works for me!
```
let datatable = new simpleDatatables.DataTable("#myTable", {
    plugins: {
        myPlugin: {
            // Prevent plugin from being initialised
            enabled: false
        }
    }
});
```

**Comment by johanneswilm** [comment]
fixed in latest version

**Comment by amirakbulut** [comment]
I'm still having this issue using the following configuration:

`https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css`
`https://cdn.jsdelivr.net/npm/simple-datatables@latest`

```
let dataTable = new simpleDatatables.DataTable("#myTable", {
    searchable: false,
    fixedHeight: true
});
```

Which results in:

```
simple-datatables.js:8 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at new s.DataTable (simple-datatables.js:8:8899)
    at <anonymous>:1:17
```
